---
parameters:
  compiler: ""
  options: ""
  workdir: "autotools-build"

steps:
  - bash: |
      export COMPILER=${{ parameters.compiler }}
      case ${COMPILER:-default} in
        clang ) export CC=clang CXX=clang++ ;;
        gcc   ) export CC=gcc   CXX=g++     ;;
      esac
      mkdir '${{ parameters.workdir }}' && cd "$_"
      ../autogen.sh ${{ parameters.options }}
    displayName: 'Configuration (Autotools)'
  - bash: make -j$(nproc)
    displayName: 'Build (Autotools)'
    workingDirectory: ${{ parameters.workdir }}
  - bash: make check
    displayName: 'Tests (Autotools)'
    workingDirectory: ${{ parameters.workdir }}
  - bash: |
      shopt -s nullglob
      for file in "$(pwd)"/*.log ; do
        echo "##vso[task.uploadfile]${file}"
      done
    displayName: 'Save Results (Autotools)'
    condition: always()
