---
parameters:
  compiler: "cc"
  options: ""
  wrapper: ""
  workdir: "meson-build"
  prepare: ""

steps:
  - script: |
      ${{ parameters.prepare }}
      meson setup "${{ parameters.workdir }}" ${{ parameters.options }}
    displayName: 'Configuration'
    env:
      CC: ${{ parameters.compiler }}
  - script: |
      ${{ parameters.prepare }}
      ninja
    displayName: 'Build'
    workingDirectory: ${{ parameters.workdir }}
    env:
      TERM: dumb
  - script: |
      meson test --print-errorlogs --wrap="${{ parameters.wrapper }}"
    displayName: 'Run Tests'
    workingDirectory: ${{ parameters.workdir }}
  - bash: |
      shopt -s nullglob
      for file in "$(pwd)"/meson-logs/* ; do
        echo "##vso[task.uploadfile]${file}"
      done
      for file in "$(pwd)"/meson-logs/*.json ; do
        python3 ../scripts/meson-junit-report.py --project-name=xkbcommon \
          --job-id='$(Build.BuildId)' --branch='$(Build.SourceBranch)' \
          --output="${file}-junit.xml" "${file}"
      done
    displayName: 'Process Test Results'
    workingDirectory: ${{ parameters.workdir }}
    condition: always()
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/*-junit.xml'
      failTaskOnFailedTests: true
