---
trigger:
  - ci-azure

jobs:
  - job: 'Meson'
    dependsOn: []
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure-pipelines/steps/dependencies-linux.yml
      - template: .azure-pipelines/steps/meson.yml
        parameters:
          options: -Denable-wayland=false
  - job: 'Autotools'
    dependsOn: []
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure-pipelines/steps/dependencies-linux.yml
      - template: .azure-pipelines/steps/autotools.yml
